
import os

filepath = r"d:\Drive E\TNECL\backend\create_full_json.py"

sheet9_full = """
# Sheet 9
add_sheet("Sheet9", [
    { "Sno": 1, "Code": 9101, "CollegeName": "A.R.J. College of Engineering and Technology", "Website": "", "Location": "" },
    { "Sno": 2, "Code": 9102, "CollegeName": "Akshaya College of Engineering & Technology", "Website": "", "Location": "" },
    { "Sno": 3, "Code": 9103, "CollegeName": "Angapa College of Engineering", "Website": "", "Location": "" },
    { "Sno": 4, "Code": 9104, "CollegeName": "Angel College of Engineering & Technology", "Website": "", "Location": "" },
    { "Sno": 5, "Code": 9105, "CollegeName": "Arjun College of Technology", "Website": "", "Location": "" },
    { "Sno": 6, "Code": 9106, "CollegeName": "Asian College of Engineering and Technology", "Website": "", "Location": "" },
    { "Sno": 7, "Code": 9107, "CollegeName": "C M S College of Engineering and Technology", "Website": "", "Location": "" },
    { "Sno": 8, "Code": 9108, "CollegeName": "Cheran College of Engineering", "Website": "", "Location": "" },
    { "Sno": 9, "Code": 9109, "CollegeName": "Dhanalakshmi Srinivasan College of Engineering", "Website": "", "Location": "" },
    { "Sno": 10, "Code": 9110, "CollegeName": "Dhanalakshmi Srinivasan Institute of Research and Technology", "Website": "", "Location": "" },
    { "Sno": 11, "Code": 9111, "CollegeName": "Dhirajlal Gandhi College of Technology", "Website": "", "Location": "" },
    { "Sno": 12, "Code": 9112, "CollegeName": "Dr. Nagarathinam's College of Engineering", "Website": "", "Location": "" },
    { "Sno": 13, "Code": 9113, "CollegeName": "Government College of Engineering - Bargur", "Website": "", "Location": "" },
    { "Sno": 14, "Code": 9114, "CollegeName": "Er.Perumal Manimekalai College of Engineering", "Website": "", "Location": "" },
    { "Sno": 15, "Code": 9115, "CollegeName": "Jayalakshmi Institute of Technology", "Website": "", "Location": "" },
    { "Sno": 16, "Code": 9116, "CollegeName": "Jayam College of Engineering & Technology", "Website": "", "Location": "" },
    { "Sno": 17, "Code": 9117, "CollegeName": "Knowledge Business School, KIOT Campus", "Website": "", "Location": "" },
    { "Sno": 18, "Code": 9118, "CollegeName": "Knowledge Institute of Technology, KIOT Campus", "Website": "", "Location": "" },
    { "Sno": 19, "Code": 9120, "CollegeName": "Mahendra Engineering College", "Website": "", "Location": "" },
    { "Sno": 20, "Code": 9121, "CollegeName": "Mahendra Engineering College For Women", "Website": "", "Location": "" },
    { "Sno": 21, "Code": 9122, "CollegeName": "Mahendra Institute of Engineering &Technology", "Website": "", "Location": "" },
    { "Sno": 22, "Code": 9123, "CollegeName": "Mahendra Institute of Technology", "Website": "", "Location": "" },
    { "Sno": 23, "Code": 9124, "CollegeName": "Narasu's Sarathy Institute of Technology", "Website": "", "Location": "" },
    { "Sno": 24, "Code": 9125, "CollegeName": "P.S.V. College of Engineering & Technology", "Website": "", "Location": "" },
    { "Sno": 25, "Code": 9126, "CollegeName": "Sapthagiri College of Engineering", "Website": "", "Location": "" },
    { "Sno": 26, "Code": 9127, "CollegeName": "Sengunthar College of Engineering", "Website": "", "Location": "" },
    { "Sno": 27, "Code": 9128, "CollegeName": "Sengunthar Engineering College", "Website": "", "Location": "" },
    { "Sno": 28, "Code": 9129, "CollegeName": "Shree Sathyam College Of Engineering & Technology", "Website": "", "Location": "" },
    { "Sno": 29, "Code": 9130, "CollegeName": "Sri Venkateswara Institute of Engineering", "Website": "", "Location": "" },
    { "Sno": 30, "Code": 9131, "CollegeName": "The Kavery College of Engineering", "Website": "", "Location": "" },
    { "Sno": 31, "Code": 9132, "CollegeName": "The Kavery Engineering College", "Website": "", "Location": "" },
    { "Sno": 32, "Code": 9133, "CollegeName": "Varuvan Vadivelan Institute of Technology", "Website": "", "Location": "" },
    { "Sno": 33, "Code": 9134, "CollegeName": "Vivekanandha College of Engineering For Women", "Website": "", "Location": "" },
    { "Sno": 34, "Code": 9135, "CollegeName": "Vivekanandha College of Technology For Women", "Website": "", "Location": "" },
    { "Sno": 35, "Code": 9136, "CollegeName": "Vivekandha Institute of Information & Management Studies", "Website": "", "Location": "" },
    { "Sno": 36, "Code": 9137, "CollegeName": "Adhiyamaan College of Engineering", "Website": "", "Location": "" },
    { "Sno": 37, "Code": 9138, "CollegeName": "A V S Engineering College", "Website": "", "Location": "" },
    { "Sno": 38, "Code": 9139, "CollegeName": "Annai Mathammal Sheela Engineering College", "Website": "", "Location": "" },
    { "Sno": 39, "Code": 9140, "CollegeName": "Bharathiyar Institute of Engineering For Women", "Website": "", "Location": "" },
    { "Sno": 40, "Code": 9141, "CollegeName": "Brahma School of Business", "Website": "", "Location": "" },
    { "Sno": 41, "Code": 9142, "CollegeName": "CMS College of Engineering", "Website": "", "Location": "" },
    { "Sno": 42, "Code": 9143, "CollegeName": "Ganesh College of Engineering", "Website": "", "Location": "" },
    { "Sno": 43, "Code": 9144, "CollegeName": "Gnanamani College of Engineering", "Website": "", "Location": "" },
    { "Sno": 44, "Code": 9145, "CollegeName": "Gnanamani College of Technology", "Website": "", "Location": "" },
    { "Sno": 45, "Code": 9146, "CollegeName": "Gnanamani Institute of Management Studies", "Website": "", "Location": "" },
    { "Sno": 46, "Code": 9147, "CollegeName": "Greentech College of Engineering For Women", "Website": "", "Location": "" },
    { "Sno": 47, "Code": 9148, "CollegeName": "Idaya Engineering College For Women", "Website": "", "Location": "" },
    { "Sno": 48, "Code": 9149, "CollegeName": "King College of Technology", "Website": "", "Location": "" },
    { "Sno": 49, "Code": 9150, "CollegeName": "Kongunadu College of Engineering &Technology", "Website": "", "Location": "" },
    { "Sno": 50, "Code": 9151, "CollegeName": "Maha Barathi Engineering College", "Website": "", "Location": "" },
    { "Sno": 51, "Code": 9152, "CollegeName": "Mahendra College of Engineering", "Website": "", "Location": "" },
    { "Sno": 52, "Code": 9153, "CollegeName": "Muthayammal Engineering College", "Website": "", "Location": "" },
    { "Sno": 53, "Code": 9154, "CollegeName": "Muthayammal Technical Campus", "Website": "", "Location": "" },
    { "Sno": 54, "Code": 9155, "CollegeName": "P G P College of Engineering & Technology", "Website": "", "Location": "" },
    { "Sno": 55, "Code": 9156, "CollegeName": "Paavaai College of Engineering", "Website": "", "Location": "" },
    { "Sno": 56, "Code": 9157, "CollegeName": "Paavai Engineering College", "Website": "", "Location": "" },
    { "Sno": 57, "Code": 9158, "CollegeName": "Pavai College of Technology", "Website": "", "Location": "" },
    { "Sno": 58, "Code": 9159, "CollegeName": "S R S College of Engineering & Technology", "Website": "", "Location": "" },
    { "Sno": 59, "Code": 9160, "CollegeName": "Salem College of Engineering & Technology", "Website": "", "Location": "" },
    { "Sno": 60, "Code": 9161, "CollegeName": "Selvam College of Technology", "Website": "", "Location": "" },
    { "Sno": 61, "Code": 9162, "CollegeName": "Shreenivasa Engineering College", "Website": "", "Location": "" },
    { "Sno": 62, "Code": 9163, "CollegeName": "SRG Engineering College", "Website": "", "Location": "" },
    { "Sno": 63, "Code": 9164, "CollegeName": "Sri Ganesh School of Business Management", "Website": "", "Location": "" },
    { "Sno": 64, "Code": 9165, "CollegeName": "T.S.M. Jain College of Technology", "Website": "", "Location": "" },
    { "Sno": 65, "Code": 9166, "CollegeName": "Tagore Institute of Engineering & Technology", "Website": "", "Location": "" },
    { "Sno": 66, "Code": 9167, "CollegeName": "V S A Educational & Charitable Trust's Group of Institutions", "Website": "", "Location": "" },
    { "Sno": 67, "Code": 9168, "CollegeName": "Vasavi Vidya Trust Group of Institutions", "Website": "", "Location": "" },
    { "Sno": 68, "Code": 9169, "CollegeName": "Vetri Vinayaha College of Engineering & Technology", "Website": "", "Location": "" },
    { "Sno": 69, "Code": 9170, "CollegeName": "K. S. Rangasamy College of Technology", "Website": "", "Location": "" },
    { "Sno": 70, "Code": 9171, "CollegeName": "Government College of Engineering - Salem", "Website": "", "Location": "" },
    { "Sno": 71, "Code": 9172, "CollegeName": "Sona College of Technology", "Website": "", "Location": "" },
    { "Sno": 72, "Code": 9201, "CollegeName": "A G N College of Technology", "Website": "", "Location": "" },
    { "Sno": 73, "Code": 9202, "CollegeName": "A I S T Engineering College", "Website": "", "Location": "" },
    { "Sno": 74, "Code": 9203, "CollegeName": "A K T Memorial College of Engineering & Technology", "Website": "", "Location": "" },
    { "Sno": 75, "Code": 9204, "CollegeName": "Adithya Institute of Technology", "Website": "", "Location": "" },
    { "Sno": 76, "Code": 9205, "CollegeName": "Akshaya College of Engineering & Technology", "Website": "", "Location": "" },
    { "Sno": 77, "Code": 9206, "CollegeName": "Angappa College of Engineering", "Website": "", "Location": "" },
    { "Sno": 78, "Code": 9207, "CollegeName": "Angel College of Engineering & Technology", "Website": "", "Location": "" },
    { "Sno": 79, "Code": 9208, "CollegeName": "Arjun College of Technology", "Website": "", "Location": "" },
    { "Sno": 80, "Code": 9209, "CollegeName": "Asian College of Engineering and Technology", "Website": "", "Location": "" },
    { "Sno": 81, "Code": 9320, "CollegeName": "K S R College of Engineering", "Website": "", "Location": "" },
    { "Sno": 82, "Code": 9321, "CollegeName": "K.S.Rangasamy College of Technology", "Website": "", "Location": "" },
    { "Sno": 83, "Code": 9322, "CollegeName": "S.S.M. College of Engineering", "Website": "", "Location": "" },
    { "Sno": 84, "Code": 9323, "CollegeName": "SNS College of Engineering", "Website": "", "Location": "" },
    { "Sno": 85, "Code": 9324, "CollegeName": "SNS College of Technology", "Website": "", "Location": "" },
    { "Sno": 86, "Code": 9325, "CollegeName": "Sri Ramakrishna Engineering College", "Website": "", "Location": "" },
    { "Sno": 87, "Code": 9326, "CollegeName": "Sri Ramakrishna Institute of Technology", "Website": "", "Location": "" },
    { "Sno": 88, "Code": 9327, "CollegeName": "Sri Shakthi Institute of Engineering and Technology", "Website": "", "Location": "" },
    { "Sno": 89, "Code": 9328, "CollegeName": "Velalar College of Engineering and Technology", "Website": "", "Location": "" },
    { "Sno": 90, "Code": 9329, "CollegeName": "Vivekanandha College of Engineering for Women", "Website": "", "Location": "" },
    { "Sno": 91, "Code": 9330, "CollegeName": "Vivekanandha Institute of Engineering and Technology for Women", "Website": "", "Location": "" },
    { "Sno": 92, "Code": 9531, "CollegeName": "University College of Engineering, Ariyalur", "Website": "", "Location": "" },
    { "Sno": 93, "Code": 9532, "CollegeName": "University College of Engineering, Dindigul", "Website": "", "Location": "" },
    { "Sno": 94, "Code": 9533, "CollegeName": "University College of Engineering, Ramanathapuram", "Website": "", "Location": "" },
    { "Sno": 95, "Code": 9534, "CollegeName": "University College of Engineering, Thirukkuvalai", "Website": "", "Location": "" },
    { "Sno": 96, "Code": 9535, "CollegeName": "University College of Engineering, Pattukkottai", "Website": "", "Location": "" },
    { "Sno": 97, "Code": 9536, "CollegeName": "University College of Engineering, Villupuram", "Website": "", "Location": "" },
    { "Sno": 98, "Code": 9537, "CollegeName": "University College of Engineering, Tindivanam", "Website": "", "Location": "" },
    { "Sno": 99, "Code": 9538, "CollegeName": "University College of Engineering, Arni", "Website": "", "Location": "" },
    { "Sno": 100, "Code": 9539, "CollegeName": "University College of Engineering, Kanchipuram", "Website": "", "Location": "" },
    { "Sno": 101, "Code": 9540, "CollegeName": "University College of Engineering, Tiruchirappalli", "Website": "", "Location": "" },
    { "Sno": 102, "Code": 9541, "CollegeName": "University College of Engineering, Panruti", "Website": "", "Location": "" },
    { "Sno": 103, "Code": 9542, "CollegeName": "University College of Engineering, Thoothukudi", "Website": "", "Location": "" },
    { "Sno": 104, "Code": 9543, "CollegeName": "University College of Engineering, Nagercoil", "Website": "", "Location": "" },
    { "Sno": 105, "Code": 9544, "CollegeName": "University College of Engineering, BIT Campus", "Website": "", "Location": "" },
    { "Sno": 106, "Code": 9601, "CollegeName": "Government Engineering College - Dharmapuri", "Website": "", "Location": "" },
    { "Sno": 107, "Code": 9602, "CollegeName": "Government Engineering College - Thanjavur", "Website": "", "Location": "" },
    { "Sno": 108, "Code": 9603, "CollegeName": "Government Engineering College - Srirangam", "Website": "", "Location": "" },
    { "Sno": 109, "Code": 9604, "CollegeName": "Government Engineering College - Ariyalur", "Website": "", "Location": "" },
    { "Sno": 110, "Code": 9605, "CollegeName": "Government Engineering College - Pattukkottai", "Website": "", "Location": "" },
    { "Sno": 111, "Code": 9606, "CollegeName": "Government Engineering College - Thirukkuvalai", "Website": "", "Location": "" },
    { "Sno": 112, "Code": 9607, "CollegeName": "Government Engineering College - Villupuram", "Website": "", "Location": "" },
    { "Sno": 113, "Code": 9608, "CollegeName": "Government Engineering College - Tindivanam", "Website": "", "Location": "" },
    { "Sno": 114, "Code": 9611, "CollegeName": "Government Engineering College - Tiruchirappalli", "Website": "", "Location": "" },
    { "Sno": 115, "Code": 9612, "CollegeName": "Government Engineering College - Panruti", "Website": "", "Location": "" },
    { "Sno": 116, "Code": 9613, "CollegeName": "Government Engineering College - Thoothukudi", "Website": "", "Location": "" },
    { "Sno": 117, "Code": 9614, "CollegeName": "Government Engineering College - Nagercoil", "Website": "", "Location": "" },
    { "Sno": 118, "Code": 9615, "CollegeName": "Government Engineering College - BIT Campus", "Website": "", "Location": "" },
    { "Sno": 119, "Code": 9616, "CollegeName": "Government Engineering College - Coimbatore", "Website": "", "Location": "" },
    { "Sno": 120, "Code": 9617, "CollegeName": "Government Engineering College - Salem", "Website": "", "Location": "" },
    { "Sno": 121, "Code": 9618, "CollegeName": "Government Engineering College - Bargur", "Website": "", "Location": "" },
    { "Sno": 122, "Code": 9619, "CollegeName": "Government Engineering College - Karur", "Website": "", "Location": "" },
    { "Sno": 123, "Code": 9620, "CollegeName": "Government Engineering College - Erode", "Website": "", "Location": "" },
    { "Sno": 124, "Code": 9621, "CollegeName": "Government Engineering College - Dharmapuri", "Website": "", "Location": "" },
    { "Sno": 125, "Code": 9622, "CollegeName": "Government Engineering College - Thanjavur", "Website": "", "Location": "" }
])

with open('official_colleges.json', 'w') as f:
    json.dump(data, f, indent=2)

print("Created official_colleges.json with full 480+ records")
"""

with open(filepath, 'a') as f:
    f.write(sheet9_full)
